const kadunaWards = {
  "Birnin Gwari": [
    "Dogon Dawa",
    "Gayam",
    "Gwaska",
    "Kakangi",
    "Kamfanin Doka",
    "Kuduru",
    "Kungi",
    "Magajin Gari I",
    "Magajin Gari II",
    "Randagi",
  ],
  Chikun: [
    "Kujama",
    "Narayi",
    "Sabon Tasha",
    "Chikun",
    "Kakau",
    "Kakuri Gwari",
    "Kujama",
    "Nasarawa",
    "Rijana",
    "Sabon Tasha",
    "Unguwan Yelwa",
  ],
  Giwa: [
    "Giwa",
    "Kadage",
    "Galadimawa",
    "Idasu",
    "Kidandan",
    "Pan Hauya",
    "Shika",
    "Yakawada",
  ],
  Igabi: [
    "Afaka",
    "Birnin Yero",
    "Fanoni",
    "Igabi",
    "Kerawa",
    "Kwarau",
    "Rigachikun",
    "Rigasa",
    "Sabon Birni",
    "Turunku",
  ],
  Ikara: [
    "Auchan",
    "Ikara",
    "Jaga",
    "Kurmin Kogi",
    "Kuya",
    "Paki",
    "Rumi",
    "Saulawa",
  ],
  Jaba: [
    "Dura/Bitaro",
    "Fai",
    "Chori",
    "Daddu",
    "Fada",
    "Sabon Sarki",
    "Sabzuro",
    "Samban",
    "Ungwan Bako",
  ],
  "Jema'a": [
    "Dangoma",
    "Jagindi",
    "Kafanchan A",
    "Kafanchan B",
    "Kaninkon",
    "Kagoma",
    "Takau",
    "Godogodo",
  ],
  Kachia: [
    "Agunu",
    "Awon",
    "Bishini",
    "Doka",
    "Gidan Tagwai",
    "Gidan Gayan",
    "Gumel",
    "Kachia Urban",
    "Kurmin Musa",
  ],
  "Kaduna North": [
    "Badarawa",
    "Doka",
    "Gabasawa",
    "Gwari Road",
    "Kawo",
    "Shaba",
    "Unguwan Dosa",
    "Unguwan Liman",
  ],
  "Kaduna South": [
    "Barnawa",
    "Makera",
    "Television",
    "Tudun Wada South",
    "Tudun Wada North",
    "Unguwan Muazu",
    "Kakuri Gwari",
    "Kaduna Polytechnic",
  ],
  Kagarko: [
    "Idah",
    "Igu",
    "Jere",
    "Kagarko",
    "Katugal",
    "Kufana",
    "Kurmin Jibrin",
    "Kushe",
  ],
  Kajuru: [
    "Afogo",
    "Buda",
    "Idon",
    "Kajuru",
    "Kasuwan Magani",
    "Maro",
    "Rimau",
  ],
  Kaura: ["Bondong", "Fada", "Kadarko", "Kaura", "Kpak", "Manchok", "Zankan"],
  Kauru: [
    "Bakin Kogi",
    "Dawaki",
    "Kadage",
    "Kandam",
    "Kurum",
    "Kuzuntu",
    "Makami",
    "Pambeguwa",
  ],
  Kubau: [
    "Anchau",
    "Damau",
    "Dutsen Wai",
    "Haskiya",
    "Kargi",
    "Kubau",
    "Pambegua",
    "Zuntu",
  ],
  Kudan: ["Dora", "Garu", "Hunkuyi", "Kudan", "Likoro", "Matsirga", "Taba"],
  Lere: [
    "Abadawa",
    "Daka",
    "Gure",
    "Kayarda",
    "Lere",
    "Mazuga",
    "Sabon Birni",
    "Saminaka",
  ],
  Makarfi: [
    "Dandamisa",
    "Gimi",
    "Gubuchi",
    "Kadage",
    "Makarfi",
    "Nashemba",
    "Tashan Iche",
  ],
  "Sabon Gari": ["Bomo", "Chikaji", "Dogarawa", "Jama'a", "Muchia", "Samaru"],
  Sanga: [
    "Aboro",
    "Bokana",
    "Fadan Karshi",
    "Gwantu",
    "Kigon",
    "Nandu",
    "Ninzam",
  ],
  Soba: [
    "Dan Wata",
    "Gamagira",
    "Garun Kurama",
    "Maigana",
    "Rahama",
    "Richifa",
    "Soba",
  ],
  "Zangon Kataf": [
    "Atak Njei",
    "Gora",
    "Kamaru",
    "Madakiya",
    "Zango",
    "Zonzon",
  ],
  Zaria: [
    "Dutsen Abba",
    "Gyallesu",
    "Kaura",
    "Kwarbai A",
    "Kwarbai B",
    "Limancin Kona",
    "Tudun Wada",
    "Zaria City",
  ],
};

module.exports = kadunaWards;
